### ISSUE TITLE
No sound on Android tablet

### ISSUE THREAD

**Issue by DLMcPherson** [ehgoodenough/rodomopo#1]
When I use RoDoMoPo on my Android Tablet (model A1X Plus), no sound plays when the timer terminates.

**Comment by ehgoodenough** [comment]
An unfortunate issue; webapps aren't granted access to audio on mobile devices. What needs to be done is "natively" deploy the app using cordova. If we do that, [we can use one of their plugins to play the sounds](http://docs.phonegap.com/en/edge/cordova_media_media.md.html).

Thanks for reporting this!

**Comment by ehgoodenough** [comment]
[WebAudio is now natively supported in mobile browsers, including Android.](https://caniuse.com/#feat=audio)

Resolving this issue (...Almost three years later)
